apply plugin: 'com.android.library'

android {
    namespace "app.lovable.tvoff.plugin"
    compileSdk 35

    defaultConfig {
        minSdk 24
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation "androidx.appcompat:appcompat:1.7.0"
}

repositories {
    google()
    mavenCentral()
}
